USE [testBD]
GO

/****** Object:  Table [dbo].[testRes]    Script Date: 26.09.2025 19:07:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[testRes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[X1] [float] NOT NULL,
	[X2] [float] NOT NULL,
	[X] [float] NOT NULL,
	[Date] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[testRes] ADD  DEFAULT (getdate()) FOR [Date]
GO

